### ISSUE TITLE
Fix this ugly bitch pls...

### ISSUE THREAD

**Issue by CarstenKoenig** [MoritzGrossmann/devopenspace-elm-todo#15]
![CssIsFun](https://user-images.githubusercontent.com/1927108/65374494-ccbc4980-dc8a-11e9-9084-1309481b8182.png)

**Comment by MoritzGrossmann** [comment]
hab da leider grad ein Problem. Entweder ich mach die ganze app breiter oder ich hol die überschrift aus dem App-Container raus und fummel da bisschen rum. Leider ist das css der Todo-App nicht für so große überschriften gemacht. Erste Lösung wäre schnell gemacht und jetzt net soo schlimm. 2. Lösung wäre schon ziemlich aufwendig,

**Comment by CarstenKoenig** [comment]
ja stimmt - vielleicht den Titel "splitten" und zur Not abschneiden (mit `...`)?
