### ISSUE TITLE
Fahrplan

### ISSUE THREAD

**Issue by CarstenKoenig** [MoritzGrossmann/devopenspace-elm-todo#21]
Ich würde hier gerne unseren *Fahrplan* diskutieren.

Erster Vorschlag:

## Schritt 1

- [x] Fertig (Branch Step1)

Kurzeinführung in Elm und die Tools - Teilnehmer laden sich das *Startprojekt* herunter und lassen es bauen

## Schritt 2

- [x] Fertig (Branch Step2-Login)
- [x] Übung (Branch Step2-Uebung)

Basis-Elm-Architektur (Model View Update) - Wir bauen oder zeigen die "Login" Seite direkt 

Übung für die Teilnehmer: OK disabled wenn eine Eingabe leer ist

## Schritt 3

- [x] Fertig (Branch Step3-Kommunikation)
- [x] Übung (Branch Step3-Uebung)

Commands - wir bauen das Login so aus, dass das Backend verwendet wird (hier können wir Module und deren Aufbau, z.B. das Auth. Modul vorstellen und die Idee hinter Session und Flags erklären, Teilnehmer sollen das Register selber bauen und ausprobieren)

## Schritt 4

- [x] Fertig (Branch Step4-Navigation)
- [x] Übungsseite (Branch Step4-Uebung)

Navigation - wir bauen die Main zu einer Login-Page um und führen die vollständige Applikation mit Navigation ein (erklären NavKey, Routen, Page Model, Interaktion mit Sessions - *Diskussion:* Pages **sind** vollständige Komponenten mit `update`, `view`, `subscription`,...) - die Teilnehmer sollen versuchen eine zusätzliche Seite für die Task-Listen selbst hinzuzufügen (ohne Inhalt)

## Schritt 5

- [x] Fertig (Branch Step5-TaskListen)

Wir füllen gemeinsam die Task-Liste mit leben - hier können wir die Idee, dass ich Dir Code paste gut nutzen - so gehen wir das Modul langsam durch und erklären was nötig ist

## Schritt 6

- [x] Fertig (Branch Step6-LocalStorage)

LocalStorage - wir erklären Ports und zeigen wie das Token aus dem Local-Storage geladen wird

## Schritt 7

- [x] Fertig (Branch Step7-TaskAnsicht)

Wir ergänzen die Task-Ansicht und besprechen was nötig ist

## Schritt 8

- [x] Fertig (Branch Step8-Statusleiste)

Als Übung sollen die Teilnehmer eine Status-Leiste bauen, wo der eingeloggte Benutzer angezeigt wird und Logout (einfach auf Login linken) ausgeführt werden kann - hier braucht man keine Komponente, eine einfache Funktion reicht, die in jeder Seite die das nötig hat benutzt werden kann

## 9. Abschlussdiskussion

----

Was bleibt: 

- ~die Register-Seite müssen wir noch einbauen (mache ich)~
- ~der Benutzer-Header für 8 muss noch eingebaut werden (kannst Du das machen?)~
- ~Wir müssen die App in die Teile oben zerlegen und Tags/Branches anlegen (wer macht das?)~
- ~Teilweise haben sich noch "Metadaten"-Namen verirrt und müssen umbenannt werden (hatte ich vergessen - wer macht das?)~

- alle Steps müssten einzeln getestet werden (Kompiliert/Läuft die App dort?) - Kompiliert hatte ich geprüft, Laufzeitverhalten ehrlich gesagt nicht

Bitte um Kommentar - danke.

**Comment by MoritzGrossmann** [comment]
klingt gut so.
Die App zerlegen kann ich machen. 
was meinst du mit den Metadaten-Namen?

**Comment by CarstenKoenig** [comment]
z.B. hier: https://github.com/MoritzGrossmann/devopenspace-elm-todo/blob/273c8ccabfd90c71ac027d34e39d2fbb5d7f5c87/Elm/src/Page/TaskList.elm#L51

Ich denke Du hast das mit eingebaut - wir dachten damals, dass wir zwei verschiedene List-Darstellungen brauchen, deswegen hattest Du das aufgetrennt in einen Teil ohne Tasks (die Metadaten) und die Liste aus Metadaten und Tasks

Stellt sich aber heraus, dass die Tasks niemals benutzt wurden, weshalb ich das verworfen und die Metadaten in TaskList umbenannt habe ... nur leider sind mir ein paar von den Begriffen nicht aufgefallen

**Comment by CarstenKoenig** [comment]
Bevor wir die App zerlegen sollten wir noch die Register-Alternative und den Header einbauen - ich mache mich gleich noch an das Registrieren - wäre geil wenn Du den Header machst (ich hasse das CSS Zeugs und Du bist da fitter)

**Comment by CarstenKoenig** [comment]
Register - siehe https://github.com/MoritzGrossmann/devopenspace-elm-todo/pull/22

**Comment by CarstenKoenig** [comment]
Meta entfernt - siehe https://github.com/MoritzGrossmann/devopenspace-elm-todo/pull/23

**Comment by MoritzGrossmann** [comment]
willst du mit dem header sowas wie ne navbar?

**Comment by CarstenKoenig** [comment]
ja nur ohne Nav (denke ich) - einfach nur als Übung, damit auf der Liste / Tasks Seite oben erkennbar ist wer angemeldet ist und ein Link auf `/login` gemacht wird (zum Ausloggen)

**Comment by MoritzGrossmann** [comment]
jo mach ich. Würde bei logout auch den auth-key aus dem LS löschen

**Comment by CarstenKoenig** [comment]
brauchst Du nicht - beim `init` im Login wird das schon gemacht

**Comment by CarstenKoenig** [comment]
@MoritzGrossmann ich habe die Aufteilung fertig - allerdings müssten wir alle Steps nochmal prüfen (sind alles Branches - von `Step1`, `Step2-..` bis `Step8-`... und dann einer `Endfassung` und ein `Komplett` wo das Backend/Docker drin ist - das sollte eigentlich auf Stand `master` sein)

Wenn alles stimmt können wir dann den `master` auf den `Step1` setzen

Was meinst Du - sieht das so ok für Dich aus?
