### ISSUE TITLE
Diskussion: Tasks-API - irrelevante ListId

### ISSUE THREAD

**Issue by CarstenKoenig** [MoritzGrossmann/devopenspace-elm-todo#6]
für die PUT, DELETE und GET / TaskId Routen ist die Listen-Id eigentlich irrelevant - wollen wir die URLs an der stelle auftrennen und für die 3 Dinge den `list/{listId}`-Part weglassen?

**Comment by MoritzGrossmann** [comment]
ist eine gute idee. Ich fande es rein für die Funktionalität auch irrelevant. Sinnvoll ist es nur wenn man die API REST-Konformer machen will. Also nur zu. Ich ändere es auf meiner Seite ab
